name: Update

on:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: update
        env:
          MY_BREW_KEY: ${{ secrets.MY_BREW_KEY }}
        run: |
          echo 111111
#          chmod +x update.sh
#          ./update.sh
#          git diff --quiet && git diff --cached --quiet
#          if git diff --quiet && git diff --cached --quiet; then
#            echo "No changes detected"
#          else
#            mkdir -p ~/.ssh
#            echo "$MY_BREW_KEY" > ~/.ssh/id_rsa
#            chmod 600 ~/.ssh/id_rsa
#            ssh-keyscan github.com >> ~/.ssh/known_hosts
#            git config --global user.name "lostars"
#            git config --global user.email "bot@minei.me"
#            git add Casks/*
#            git commit -m 'cron updates'
#            git push
#          fi