name: Update

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: update
        env:
          MY_BREW_KEY: ${{ secrets.MY_BREW_KEY }}
        run: |
          chmod +x update.sh
          ./update.sh
          status=""
          statusFile=output/status.txt
          if [ -f "$statusFile" ]; then
            status=$(cat "$statusFile")
          fi
          if [ "$status" == "true" ]; then
            mkdir -p ~/.ssh
            echo "$MY_BREW_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.name "lostars"
            git config --global user.email "746320542jn@gmail.com"
            git add Casks/*
            message=$(cat output/message.txt)
            git commit -m "$message"
            git push git@github.com:${{ github.repository }}.git
          fi