name: Update

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: update
        env:
          MY_BREW_KEY: ${{ secrets.MY_BREW_KEY }}
        run: |
          chmod +x update.sh
          ./update.sh
          status=""
          statusFile=output/status.txt
          if [ -f "$statusFile" ]; then
            status=$(cat "$statusFile")
          fi
          if [ "$status" == "true" ]; then
            mkdir -p ~/.ssh
            echo "$MY_BREW_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
               
            while IFS= read -r line; do
              changed_file=$(echo "$line" | awk '{print $1}')
              msg=$(echo "$line" | awk '{$1=""; print substr($0, 2)}')
              echo "$changed_file"
              echo "$msg"
              git add "$changed_file"
              git commit -m "$msg"
              git push git@github.com:${{ github.repository }}.git
            done < "output/message.txt"
          fi